import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ['latin'],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
    title: "MovieDb",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} antialiased mx-10`}
            >
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
